from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("5.12.0")

configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/deg.smk"
include: "rules/correlation.smk"
include: "rules/normalization.smk"
include: "rules/qc.smk"
include: "rules/raw.smk"
include: "rules/xena.smk"
include: "rules/gdc.smk"


wildcard_constraints:
    tissue="[A-Za-z]+",
    type="normal|cancer"

rule all:
    input:
        get_output_files
