cran <- c('ggplot2', 'reshape2')
bioconductor <- c('NOISeq', 'DESeq2', 'BiocParallel', 'cqn')
chooseCRANmirror(graphics=FALSE, ind=1)
source('http://bioconductor.org/biocLite.R')
BiocInstaller::biocLite(bioconductor, ask = FALSE, suppressUpdates = TRUE, suppressAutoUpdate = TRUE, quiet = TRUE)
install.packages(cran, quiet = TRUE)
sapply(cran, require, character.only=TRUE)
sapply(bioconductor, require, character.only=TRUE)
