cran <- c('ggplot2', 'reshape2', 'mGSZ', 'gplots')
bioconductor <- c('NOISeq', 'EDASeq', 'DESeq2','edgeR', 'BiocParallel', 'org.Hs.eg.db', 'GOstats', 'cqn', 'limma')
chooseCRANmirror(graphics=FALSE, ind=1)
source('http://bioconductor.org/biocLite.R')
BiocInstaller::biocLite(bioconductor, ask = FALSE, suppressUpdates = TRUE, suppressAutoUpdate = TRUE, quiet = TRUE)
install.packages(cran, quiet = TRUE)
sapply(cran, require, character.only=TRUE)
sapply(bioconductor, require, character.only=TRUE)
